// <auto-generated />
using System;
using Incercare;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Incercare.Migrations
{
    [DbContext(typeof(LicentaContext))]
    partial class LicentaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_cerere", new[] { "in_asteptare", "aprobata", "respinsa" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_credit", new[] { "activ", "inchis", "intarziat" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_plata", new[] { "neplatita", "platita", "intarziata" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tip_client", new[] { "fizic", "juridic" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tip_notificare", new[] { "scadenta", "informativa", "urgenta" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Incercare.Brokeri", b =>
                {
                    b.Property<int>("IdBroker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_broker");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBroker"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nume")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nume");

                    b.Property<string>("ParolaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parola_hash");

                    b.Property<string>("Prenume")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenume");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefon");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenResetare")
                        .HasColumnType("text");

                    b.HasKey("IdBroker")
                        .HasName("brokeri_pkey");

                    b.HasIndex(new[] { "Email" }, "brokeri_email_key")
                        .IsUnique();

                    b.ToTable("brokeri", (string)null);
                });

            modelBuilder.Entity("Incercare.CereriCredit", b =>
                {
                    b.Property<int>("IdCerere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cerere");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCerere"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Dobanda")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("dobanda");

                    b.Property<int?>("IdBroker")
                        .HasColumnType("integer")
                        .HasColumnName("id_broker");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.Property<int?>("PerioadaLuni")
                        .HasColumnType("integer")
                        .HasColumnName("perioada_luni");

                    b.Property<decimal?>("SumaSolicitata")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("suma_solicitata");

                    b.HasKey("IdCerere")
                        .HasName("cereri_credit_pkey");

                    b.HasIndex("IdBroker");

                    b.HasIndex("IdClient");

                    b.ToTable("cereri_credit", (string)null);
                });

            modelBuilder.Entity("Incercare.Clienti", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClient"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TipClient")
                        .HasColumnType("text")
                        .HasColumnName("tip_client");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenResetare")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("IdClient")
                        .HasName("clienti_pkey");

                    b.ToTable("clienti", (string)null);
                });

            modelBuilder.Entity("Incercare.ClientiPersoaneFizice", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.Property<string>("Adresa")
                        .HasColumnType("text")
                        .HasColumnName("adresa");

                    b.Property<string>("Cnp")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("cnp");

                    b.Property<DateOnly?>("DataNastere")
                        .HasColumnType("date")
                        .HasColumnName("data_nastere");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nume")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nume");

                    b.Property<string>("ParolaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parola_hash");

                    b.Property<string>("Prenume")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenume");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefon");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenResetare")
                        .HasColumnType("text");

                    b.HasKey("IdClient")
                        .HasName("clienti_persoane_fizice_pkey");

                    b.HasIndex(new[] { "Cnp" }, "clienti_persoane_fizice_cnp_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "clienti_persoane_fizice_email_key")
                        .IsUnique();

                    b.ToTable("clienti_persoane_fizice", (string)null);
                });

            modelBuilder.Entity("Incercare.ClientiPersoaneJuridice", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.Property<string>("Adresa")
                        .HasColumnType("text")
                        .HasColumnName("adresa");

                    b.Property<string>("Cui")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cui");

                    b.Property<string>("Denumire")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("denumire");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParolaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parola_hash");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefon");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenResetare")
                        .HasColumnType("text");

                    b.HasKey("IdClient")
                        .HasName("clienti_persoane_juridice_pkey");

                    b.HasIndex(new[] { "Cui" }, "clienti_persoane_juridice_cui_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "clienti_persoane_juridice_email_key")
                        .IsUnique();

                    b.ToTable("clienti_persoane_juridice", (string)null);
                });

            modelBuilder.Entity("Incercare.Credite", b =>
                {
                    b.Property<int>("IdCredit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_credit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCredit"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataStart")
                        .HasColumnType("date")
                        .HasColumnName("data_start");

                    b.Property<decimal?>("Dobanda")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("dobanda");

                    b.Property<int?>("Durata")
                        .HasColumnType("integer")
                        .HasColumnName("durata");

                    b.Property<int?>("IdBroker")
                        .HasColumnType("integer")
                        .HasColumnName("id_broker");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.Property<int?>("IdTipCredit")
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_credit");

                    b.Property<decimal?>("Rata")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("rata");

                    b.Property<decimal?>("Suma")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("suma");

                    b.HasKey("IdCredit")
                        .HasName("credite_pkey");

                    b.HasIndex("IdBroker");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdTipCredit");

                    b.ToTable("credite", (string)null);
                });

            modelBuilder.Entity("Incercare.Documente", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_document");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocument"));

                    b.Property<string>("FisierPath")
                        .HasColumnType("text")
                        .HasColumnName("fisier_path");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.Property<string>("TipDocument")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tip_document");

                    b.Property<DateTime?>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("upload_date")
                        .HasDefaultValueSql("now()");

                    b.HasKey("IdDocument")
                        .HasName("documente_pkey");

                    b.HasIndex("IdClient");

                    b.ToTable("documente", (string)null);
                });

            modelBuilder.Entity("Incercare.LogActiuni", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_log");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Actiune")
                        .HasColumnType("text")
                        .HasColumnName("actiune");

                    b.Property<DateTime?>("DataActiune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_actiune")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.HasKey("IdLog")
                        .HasName("log_actiuni_pkey");

                    b.HasIndex("IdClient");

                    b.ToTable("log_actiuni", (string)null);
                });

            modelBuilder.Entity("Incercare.Notificari", b =>
                {
                    b.Property<int>("IdNotificare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_notificare");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificare"));

                    b.Property<DateTime?>("DataNotificare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_notificare")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("IdClient")
                        .HasColumnType("integer")
                        .HasColumnName("id_client");

                    b.Property<string>("Mesaj")
                        .HasColumnType("text")
                        .HasColumnName("mesaj");

                    b.HasKey("IdNotificare")
                        .HasName("notificari_pkey");

                    b.HasIndex("IdClient");

                    b.ToTable("notificari", (string)null);
                });

            modelBuilder.Entity("Incercare.Plati", b =>
                {
                    b.Property<int>("IdPlata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_plata");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlata"));

                    b.Property<DateOnly?>("DataPlata")
                        .HasColumnType("date")
                        .HasColumnName("data_plata");

                    b.Property<int?>("IdCredit")
                        .HasColumnType("integer")
                        .HasColumnName("id_credit");

                    b.Property<decimal?>("SumaPlatita")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("suma_platita");

                    b.HasKey("IdPlata")
                        .HasName("plati_pkey");

                    b.HasIndex("IdCredit");

                    b.ToTable("plati", (string)null);
                });

            modelBuilder.Entity("Incercare.TipuriCredite", b =>
                {
                    b.Property<int>("IdTipCredit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tip_credit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipCredit"));

                    b.Property<decimal?>("DobandaMaxima")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("dobanda_maxima");

                    b.Property<decimal?>("DobandaMinima")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("dobanda_minima");

                    b.Property<string>("NumeCredit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nume_credit");

                    b.Property<decimal?>("SumaMaxima")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("suma_maxima");

                    b.Property<decimal?>("SumaMinima")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("suma_minima");

                    b.Property<string>("TipClient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tip_client");

                    b.HasKey("IdTipCredit")
                        .HasName("tipuri_credite_pkey");

                    b.ToTable("tipuri_credite", (string)null);
                });

            modelBuilder.Entity("Incercare.CereriCredit", b =>
                {
                    b.HasOne("Incercare.Brokeri", "IdBrokerNavigation")
                        .WithMany("CereriCredits")
                        .HasForeignKey("IdBroker")
                        .HasConstraintName("cereri_credit_id_broker_fkey");

                    b.HasOne("Incercare.Clienti", "IdClientNavigation")
                        .WithMany("CereriCredits")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("cereri_credit_id_client_fkey");

                    b.Navigation("IdBrokerNavigation");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Incercare.ClientiPersoaneFizice", b =>
                {
                    b.HasOne("Incercare.Clienti", "IdClientNavigation")
                        .WithOne("ClientiPersoaneFizice")
                        .HasForeignKey("Incercare.ClientiPersoaneFizice", "IdClient")
                        .IsRequired()
                        .HasConstraintName("clienti_persoane_fizice_id_client_fkey");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Incercare.ClientiPersoaneJuridice", b =>
                {
                    b.HasOne("Incercare.Clienti", "IdClientNavigation")
                        .WithOne("ClientiPersoaneJuridice")
                        .HasForeignKey("Incercare.ClientiPersoaneJuridice", "IdClient")
                        .IsRequired()
                        .HasConstraintName("clienti_persoane_juridice_id_client_fkey");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Incercare.Credite", b =>
                {
                    b.HasOne("Incercare.Brokeri", "IdBrokerNavigation")
                        .WithMany("Credites")
                        .HasForeignKey("IdBroker")
                        .HasConstraintName("credite_id_broker_fkey");

                    b.HasOne("Incercare.Clienti", "IdClientNavigation")
                        .WithMany("Credites")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("credite_id_client_fkey");

                    b.HasOne("Incercare.TipuriCredite", "IdTipCreditNavigation")
                        .WithMany("Credites")
                        .HasForeignKey("IdTipCredit")
                        .HasConstraintName("credite_id_tip_credit_fkey");

                    b.Navigation("IdBrokerNavigation");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdTipCreditNavigation");
                });

            modelBuilder.Entity("Incercare.Documente", b =>
                {
                    b.HasOne("Incercare.Clienti", "IdClientNavigation")
                        .WithMany("Documentes")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("documente_id_client_fkey");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Incercare.LogActiuni", b =>
                {
                    b.HasOne("Incercare.Clienti", "IdClientNavigation")
                        .WithMany("LogActiunis")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("log_actiuni_id_client_fkey");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Incercare.Notificari", b =>
                {
                    b.HasOne("Incercare.Clienti", "IdClientNavigation")
                        .WithMany("Notificaris")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("notificari_id_client_fkey");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Incercare.Plati", b =>
                {
                    b.HasOne("Incercare.Credite", "IdCreditNavigation")
                        .WithMany("Platis")
                        .HasForeignKey("IdCredit")
                        .HasConstraintName("plati_id_credit_fkey");

                    b.Navigation("IdCreditNavigation");
                });

            modelBuilder.Entity("Incercare.Brokeri", b =>
                {
                    b.Navigation("CereriCredits");

                    b.Navigation("Credites");
                });

            modelBuilder.Entity("Incercare.Clienti", b =>
                {
                    b.Navigation("CereriCredits");

                    b.Navigation("ClientiPersoaneFizice");

                    b.Navigation("ClientiPersoaneJuridice");

                    b.Navigation("Credites");

                    b.Navigation("Documentes");

                    b.Navigation("LogActiunis");

                    b.Navigation("Notificaris");
                });

            modelBuilder.Entity("Incercare.Credite", b =>
                {
                    b.Navigation("Platis");
                });

            modelBuilder.Entity("Incercare.TipuriCredite", b =>
                {
                    b.Navigation("Credites");
                });
#pragma warning restore 612, 618
        }
    }
}
